name: NodeJS EKS Feature Workflow
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      component:
        required: true
        type: string
env:
  project: ${{ inputs.project }}
  component: ${{ inputs.component }}
jobs:
  build-nodejs:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v7 # this is plugin to checkout the code from the repository

      - name: read version from package.json
        id: get_version 
        run: |
            version=$(jq -r '.version' package.json)
            echo "version=${version}" >> $GITHUB_OUTPUT
      
      - name: print the version
        run: echo "The version of the application is ${{ steps.get_version.outputs.version }}"


#Turns a workflow into a reusable template (library function) that can be executed by other workflows.
#workflow_call (The Internal Intercom Page): This is a manager using the office phone to call an internal department blueprint. They dial Ext 401 (The HR Department) and say, "Execute the standard new-employee onboarding process for John Doe." The HR script didn't start because of a human button or a system fire; it was called directly by another manager to do a specific job.
